services:
  bff:
    build: ../bff

  user:
    build: ../user

  task-scheduler:
    build: ../task-scheduler

  notifier:
    build: ../notifier

  postgres:
    ports:
      - "5432:5432"

  mongo:
    ports:
      - "27017:27017"
