name: ts-system
services:
  bff:
    image: enzobbom/ts-bff:latest
    ports:
      - "8083:8083"
    environment:
      TS_USER_SERVICE_URI: http://user:8080/user
      TS_TASK_SERVICE_URI: http://task-scheduler:8081/task
      TS_NOTIFIER_SERVICE_URI: http://notifier:8082/email
      TS_CRON_USER_EMAIL: ${TS_CRON_USER_EMAIL}
      TS_CRON_USER_PASSWORD: ${TS_CRON_USER_PASSWORD}
    depends_on:
      user:
        condition: service_healthy
      task-scheduler:
        condition: service_healthy
      notifier:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

  user:
    image: enzobbom/ts-user:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ts_user
      SPRING_DATASOURCE_USERNAME: ${TS_POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${TS_POSTGRES_PASSWORD}
      TS_JWT_SECRET: ${TS_JWT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

  task-scheduler:
    image: enzobbom/ts-task-scheduler:latest
    ports:
      - "8081:8081"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/ts_task_scheduler
      TS_USER_SERVICE_URI: http://user:8080/user
      TS_JWT_SECRET: ${TS_JWT_SECRET}
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

  notifier:
    image: enzobbom/ts-notifier:latest
    ports:
      - "8082:8082"
    environment:
      TS_SMTP_EMAIL: ${TS_SMTP_EMAIL:-}
      TS_SMTP_PASSWORD: ${TS_SMTP_PASSWORD:-}
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${TS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TS_POSTGRES_PASSWORD}
      POSTGRES_DB: ts_user
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${TS_POSTGRES_USER}", "-d", "ts_user"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

  mongo:
    image: mongo:8
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: ts_task_scheduler
    healthcheck:
        test: [ "CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 }).ok" ]
        interval: 30s
        timeout: 5s
        retries: 3
        start_period: 15s

networks:
  default:
    driver: bridge
